name: nlp_stanza

channels:
  - conda-forge
  - defaults
  - stanfordnlp
dependencies:
  - python=3.9
  - pip
  - setuptools
  - numpy
  - wheel
  - pandas 
  - spacy
  - ipykernel
  - pip:
    - nltk
    - tqdm
    - bs4
    - stanza
    
# - en-core-web-sm
#- textacy

# to add this env to jupyterlab: 

#$ conda activate nlp_stanza          
#(nlp_stanza)$ conda install ipykernel
#(nlp_stanza)$ python -m ipykernel install --user --name=nlp_stanza --display-name "NLP Stanza Env"
#(nlp_stanza)$ conda deactivate